apiVersion: v1
kind: ConfigMap
metadata: 
  name: script-configmap
  namespace: argo 
data:
  get-cluster-info.sh: |
    echo "Retrieving cluster info!";
    echo "Listing non-Ready containers...";
    kubectl get pods --all-namespaces -o jsonpath='{range .items[*]}{.status.containerStatuses[*].ready.false}{.metadata.name}{ "\n"}{end}';
    echo "Printing current context...";
    kubectl config current-context;
    
