apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-workflow
  namespace: argo
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: execute-workflow
    templates:
    - name: execute-workflow
      dag:
        tasks:
        - name: first-task
          template: execute-curl
          arguments:
            parameters:
            - name: external-url
              value: "ifconfig.me"
            - name: protocol
              value: "https"
        - name: second-task
          template: execute-script
          arguments:
            parameters:
            - name: filler
              value: filler
    
    - name: execute-curl
      inputs:
        parameters:
        - name: external-url
        - name: protocol
      script:
        image: alpine/curl:3.14
        command: ["sh"]
        source: |
          echo "Executing curl...";
          curl "{{inputs.parameters.protocol}}://{{inputs.parameters.external-url}}";

    - name: execute-script
      inputs:
        parameters:
        - name: filler
      volumes:
      - name: script-vol
        configMap:
          name: script-configmap
          defaultMode: 0777
      script:
        image: alpine/k8s:1.20.7
        command: ["sh"]
        volumeMounts:
        - name: script-vol
          mountPath: /scripts
        source: |
          /scripts/get-cluster-info.sh;

