apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source: 
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: v10.9.1
    helm:
      releaseName: traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
